"use client";

import { useLiveActionState as useActionState } from "@/components/live/useLiveActionState";
import FormMessage from "@/components/ui/FormMessage";
import { reconcileRaceFinanceAction, saveFinanceDamageAction } from "@/lib/finance/actions";
import { initialFinanceActionState, type RaceFinancePreview } from "@/lib/finance/types";
import { Calculator, Save } from "lucide-react";

type ResultRow = { id: number; status: string; finalPosition: number | null; driver: { name: string }; representedTeam: { name: string }; financeDetail: { frontWingDamage: boolean; underfloorDamage: boolean; sidepodDamage: boolean; rearWingDamage: boolean } | null };

function DamageForm({ result }: { result: ResultRow }) {
  const [state, action, pending] = useActionState(saveFinanceDamageAction, initialFinanceActionState);
  return <form action={action} className="rounded-2xl border border-slate-800 bg-slate-950/40 p-4"><input type="hidden" name="raceResultId" value={result.id} /><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-white">{result.finalPosition ? `P${result.finalPosition} · ` : ""}{result.driver.name}</p><p className="mt-1 text-xs text-slate-500">{result.representedTeam.name} · {result.status}</p></div><button disabled={pending} aria-label={`Schäden für ${result.driver.name} speichern`} className="grid size-11 shrink-0 place-items-center rounded-xl border border-blue-500/30 bg-blue-500/10 text-blue-300 hover:bg-blue-500/20"><Save size={17} /></button></div><fieldset className="mt-4 grid gap-2 sm:grid-cols-2"><legend className="mb-2 text-xs font-black uppercase tracking-wider text-slate-500">Finanzrelevante Schäden</legend>{[["frontWingDamage", "Frontflügel"], ["underfloorDamage", "Unterboden"], ["sidepodDamage", "Seitenkasten"], ["rearWingDamage", "Heckflügel"]].map(([name, label]) => <label key={name} className="flex min-h-11 items-center gap-3 rounded-xl border border-slate-800 px-3 text-sm text-slate-300"><input name={name} type="checkbox" defaultChecked={Boolean(result.financeDetail?.[name as keyof NonNullable<ResultRow["financeDetail"]>])} className="size-5 accent-blue-500" />{label}</label>)}</fieldset><div className="mt-3"><FormMessage state={state} /></div></form>;
}

export default function ResultFinancePanel({ raceId, leagueId, publicationStatus, results, preview }: { raceId: number; leagueId: number; publicationStatus: string | null; results: ResultRow[]; preview: RaceFinancePreview | null }) {
  const [state, action, pending] = useActionState(reconcileRaceFinanceAction, initialFinanceActionState);
  return <details className="mt-5 rounded-2xl border border-emerald-500/25 bg-[#101720]" open><summary className="flex min-h-12 cursor-pointer items-center gap-3 px-4 py-3 font-bold text-white"><Calculator size={19} className="text-emerald-400" />Finanzabrechnung <span className={`ml-auto rounded-full px-2 py-1 text-[.65rem] uppercase tracking-wider ${preview?.needsReconciliation ? "bg-amber-500/15 text-amber-300" : preview?.settlement ? "bg-emerald-500/15 text-emerald-300" : "bg-slate-800 text-slate-400"}`}>{preview?.needsReconciliation ? "Neuabgleich nötig" : preview?.settlement ? `Berechnet · R${preview.settlement.revision}` : "Noch nicht berechnet"}</span></summary><div className="border-t border-slate-800 p-4 sm:p-5"><p className="text-sm text-slate-400">Schäden werden nur von Admins gepflegt. DNF, DSQ und Box-Aufgabe stammen aus dem Ergebnisstatus und werden nicht doppelt belastet.</p><div className="mt-4 grid gap-3 lg:grid-cols-2">{results.map((result) => <DamageForm key={result.id} result={result} />)}</div>{results.length === 0 ? <p className="mt-4 rounded-xl border border-dashed border-slate-700 p-4 text-sm text-slate-400">Noch keine Race-Ergebnisse vorhanden.</p> : null}<form action={action} className="mt-5 rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-4"><input type="hidden" name="raceId" value={raceId} /><input type="hidden" name="leagueId" value={leagueId} /><p className={`text-sm font-semibold ${preview?.ready ? "text-emerald-300" : "text-amber-300"}`}>{preview?.message ?? "Qualifying und Rennen müssen veröffentlicht sein."}</p><label className="mt-3 flex min-h-11 items-center gap-3 text-sm text-slate-300"><input type="checkbox" name="useCurrentRules" className="size-5 accent-blue-500" />Bei bewusstem Regelwechsel aktuelle Version verwenden</label><FormMessage state={state} /><button disabled={pending || !preview?.ready || publicationStatus !== "PUBLISHED"} className="wizard-primary-button mt-3 min-h-11 w-full">{preview?.settlement ? "Finanzen neu abgleichen" : "Finanzen finalisieren"}</button></form></div></details>;
}
